# Generated by Django 2.2 on 2024-02-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog0', '0004_auto_20240222_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='author',
            new_name='auther',
        ),
    ]
